<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <property name="base_collision_size_z" value="0.04" />
	<xacro:macro name="base" params="name">
		<!-- Suppression of the link between the world and the base -->
		<!--joint name="${name}_fixed_joint" type="fixed">
				<parent link="${parent}"/>
				<child link="${name}_link"/>
				<origin xyz="0 0 0.22" rpy="0 0 0" />
		</joint-->

		<link name="${name}_link">

		  <inertial>
			<mass value="50" />
			<origin xyz="0 0 0" />
			<inertia ixx="3" ixy="0" ixz="0"
					 iyy="3" iyz="0" izz="3" />
		  </inertial>

		  <visual name="${name}_visual">
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry name="${name}_visual_geom">
				<box size="0.30376 0.31322 0.24729" />
			</geometry>
		  </visual>

		  <collision name="${name}_collision">
			<origin xyz="0 0 0.01" rpy="0 0 0" />
			<geometry name="${name}_collision_geom">
				<box size="0.30376 0.31322 0.2" />
			</geometry>
		  </collision>
		</link>

		<!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
			navigation stack dedpends on this frame -->
		<link name="${name}_footprint">
		  <inertial>
			<mass value="1.0" />
			<origin xyz="0 0 0" />
			<inertia ixx="0.01" ixy="0.0" ixz="0.0"
					iyy="0.01" iyz="0.0" izz="0.01" />
		  </inertial>
		  <visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
			  <box size="0.01 0.01 0.01" />
			</geometry>
			
			<material name="Green" />
		  </visual>
		  <collision>
			<!-- represent base collision with a simple rectangular model, positioned by base_size_z s.t. top
				surface of the collision box matches the top surface of the PR2 base -->
			<origin xyz="0 0 ${0.251+base_collision_size_z/2}" rpy="0 0 0" />
			<geometry>
			  <box size="0.001 0.001 0.001" />
			</geometry>
		  </collision>
		</link>

		<joint name="${name}_footprint_joint" type="fixed">
		  <origin xyz="0 0 0.251" rpy="0 0 0" />
		  <child link="${name}_link" />
		  <parent link="${name}_footprint"/>
		</joint>
	
		<gazebo reference="${name}_link">
			<material>Gazebo/Blue</material>
		</gazebo>

	</xacro:macro>


</robot>
