<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">
	
	<!-- Include files for extensions -->
	<include filename="$(find johnny_0_description)/urdf/base/base.gazebo.xacro" />

	<property name="base_collision_size_z" value="0.04" />
	
	<!-- Warning: eye-balled values for the laser position. -->
	<property name="base_laser_x" value="0.150" />
	<property name="base_laser_y" value="0.055" />
	<property name="base_laser_z" value="0.200" />
	<property name="base_laser_size_x" value="0.06" />
	<property name="base_laser_size_y" value="0.06" />
	<property name="base_laser_size_z" value="0.03" />
	<property name="base_laser_collision_offset_z" value="0.023" />

	<xacro:macro name="base" params="name">
		<joint name="${name}_fixed_joint" type="fixed">
				<parent link="${name}_footprint"/>
				<child link="${name}_link"/>
				<origin xyz="0 0 0.22" rpy="0 0 0" />
		</joint>

		<link name="${name}_link">
		  <inertial>
			<mass value="50" />
			<origin xyz="0 0 0" />
			<inertia ixx="3" ixy="0" ixz="0"
					 iyy="3" iyz="0" izz="3" />
		  </inertial>

		  <visual name="${name}_visual">
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry name="${name}_visual_geom">
				<box size="0.30376 0.31322 0.24729" />
			</geometry>
		  </visual>

		  <collision name="${name}_collision">
			<origin xyz="0 0 0.01" rpy="0 0 0" />
			<geometry name="${name}_collision_geom">
				<box size="0.30376 0.31322 0.2" />
			</geometry>
		  </collision>
		</link>

		<!-- joint name="${name}_footprint_joint" type="fixed">
		  <origin xyz="0 0 0.251" rpy="0 0 0" />
		  <child link="${name}_link" />
		  <parent link="${name}_footprint"/>
		</joint -->
		
		<!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
			navigation stack dedpends on this frame -->
		<link name="${name}_footprint">
		  <inertial>
			<mass value="1.0" />
			<origin xyz="0 0 0" />
			<inertia ixx="0.01" ixy="0.0" ixz="0.0"
					iyy="0.01" iyz="0.0" izz="0.01" />
		  </inertial>
		  <visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
			  <box size="0.01 0.01 0.01" />
			</geometry>
			
			<material name="Green" />
		  </visual>
		  <collision>
			<!-- represent base collision with a simple rectangular model, positioned by base_size_z s.t. top
				surface of the collision box matches the top surface of the AZ3 base -->
			<origin xyz="0 0 ${0.251+base_collision_size_z/2}" rpy="0 0 0" />
			<geometry>
			  <box size="0.001 0.001 0.001" />
			</geometry>
		  </collision>
		</link>

		<!-- front laser -->
		<xacro:hokuyo_lx04_laser_v0 name="${name}_laser" parent="${name}"
			ros_topic="/sensors/base_scan" update_rate="20" min_angle="-2.2689"
			max_angle="2.2689" >
			<origin xyz="${base_laser_x} ${base_laser_y} ${base_laser_z}" 
			rpy="0 0 0" />
		</xacro:hokuyo_lx04_laser_v0>
		
		<!-- gazebo extensions -->
		<xacro:johnny_0_base_gazebo name="${name}" />
		
		<gazebo reference="${name}_link">
			<material>Gazebo/Blue</material>
		</gazebo>
		
	</xacro:macro>


</robot>
