ifaces: [can0, can1, can2]
devices:
 - L_shoulder_pan_motor
 - L_shoulder_tilt_motor
 - L_shoulder_roll_motor
 - L_elbow_tilt_motor

period: 0.01

L_shoulder_pan_motor:
  can_device_type       : UniDriveV2
  can_device_id         : 19
  joint_name            : "L_shoulder_pan_joint"
  command_variable      : "position"
  polling               : true
  active_torque_offset  : true
  convert_torque_offset : true

L_shoulder_tilt_motor:
  can_device_type       : UniDriveV2
  can_device_id         : 20
  joint_name            : "L_shoulder_tilt_joint"
  command_variable      : "position"
  polling               : true
  active_torque_offset  : true
  convert_torque_offset : true

L_shoulder_roll_motor:
  can_device_type       : UniDriveV2
  can_device_id         : 3
  joint_name            : "L_shoulder_roll_joint"
  command_variable      : "position"
  polling               : true
  active_torque_offset  : true
  convert_torque_offset : true

L_elbow_tilt_motor:
  can_device_type       : UniDriveV2
  can_device_id         : 6
  joint_name            : "L_elbow_tilt_joint"
  command_variable      : "position"
  polling               : true
  active_torque_offset  : true
  convert_torque_offset : true

