ifaces: [can0, can1, can2]
devices:
 - L_shoulder_pan_motor

L_shoulder_pan_motor:
  can_device_type       : UniDriveV2
  can_device_id         : 38
  joint_name            : "L_shoulder_pan_motor"
  command_variable      : "position"
  polling               : true
  active_torque_offset  : true
  convert_torque_offset : true

