jn0:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  head_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - neck_pan_joint
      - neck_tilt_joint

    gains:
      neck_pan_joint:  {p: 100, d: 1, i: 1, i_clamp: 1}
      neck_tilt_joint: {p: 100, d: 1, i: 1, i_clamp: 1}

  left_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - L_shoulder_pan_joint
      - L_shoulder_tilt_joint
      - L_shoulder_roll_joint
      - L_elbow_tilt_joint

    gains:
      L_shoulder_pan_joint:     {p: 100, d: 1, i: 1, i_clamp: 1}
      L_shoulder_tilt_joint:    {p: 100, d: 1, i: 1, i_clamp: 1}
      L_shoulder_roll_joint:    {p: 100, d: 1, i: 1, i_clamp: 1}
      L_elbow_tilt_joint:       {p: 100, d: 1, i: 1, i_clamp: 1}

  right_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - R_shoulder_pan_joint
      - R_shoulder_tilt_joint
      - R_shoulder_roll_joint
      - R_elbow_tilt_joint

    gains:
      R_shoulder_pan_joint:     {p: 100, d: 1, i: 1, i_clamp: 1}
      R_shoulder_tilt_joint:    {p: 100, d: 1, i: 1, i_clamp: 1}
      R_shoulder_roll_joint:    {p: 100, d: 1, i: 1, i_clamp: 1}
      R_elbow_tilt_joint:       {p: 100, d: 1, i: 1, i_clamp: 1}
