jn0:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  head_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - neck_pan_joint
      - neck_tilt_joint

    gains: # Required because we're controlling an effort interface
      neck_pan_joint:  {p: 100, d: 1, i: 1, i_clamp: 1}
      neck_tilt_joint: {p: 100, d: 1, i: 1, i_clamp: 1}
