jn0:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  neck_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - neck_pan_joint
      - neck_tilt_joint

    gains:
      neck_pan_joint:  {p: 60, d: 5, i: 10, i_clamp: 4}
      neck_tilt_joint: {p: 60, d: 5, i: 10, i_clamp: 4}

  left_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - L_shoulder_pan_joint
      - L_shoulder_tilt_joint
      - L_shoulder_roll_joint
      - L_elbow_tilt_joint

    gains:
      L_shoulder_pan_joint:     {p:  60, d: 5.0, i: 10, i_clamp: 4}
      L_shoulder_tilt_joint:    {p:  60, d: 5.0, i: 10, i_clamp: 4}
      L_shoulder_roll_joint:    {p:  60, d: 5.0, i: 10, i_clamp: 4}
      L_elbow_tilt_joint:       {p:  60, d: 5.0, i: 10, i_clamp: 4}

  right_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - R_shoulder_pan_joint
      - R_shoulder_tilt_joint
      - R_shoulder_roll_joint
      - R_elbow_tilt_joint

    gains:
      R_shoulder_pan_joint:     {p:  60, d: 5.0, i: 10, i_clamp: 4}
      R_shoulder_tilt_joint:    {p:  60, d: 5.0, i: 10, i_clamp: 4}
      R_shoulder_roll_joint:    {p:  60, d: 5.0, i: 10, i_clamp: 4}
      R_elbow_tilt_joint:       {p:  60, d: 5.0, i: 10, i_clamp: 4}

  left_gripper_up_controller:
      type: "effort_controllers/JointPositionController"
      joint: L_gripper_up_joint
      pid: {p: 10, d: 1.0, i: 0, i_clamp: 4}
       
  left_gripper_down_controller:
      type: "effort_controllers/JointPositionController"
      joint: L_gripper_down_joint
      pid: {p: 10, d: 1.0, i: 0, i_clamp: 4}

  right_gripper_up_controller:
      type: "effort_controllers/JointPositionController"
      joint: R_gripper_up_joint
      pid: {p: 10, d: 1.0, i: 0, i_clamp: 4}
       
  right_gripper_down_controller:
      type: "effort_controllers/JointPositionController"
      joint: R_gripper_down_joint
      pid: {p: 10, d: 1.0, i: 0, i_clamp: 4}
