<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


	<xacro:include filename="$(find irl_common_description)/urdf/common_geometry.xacro" />

	<xacro:macro name="box_torso" params="name parent xyz height stand_width chest_width chest_height chest_length">

		<!-- "Stand", the bar supporting the torso -->

		<joint name="${name}_stand_fixed_joint" type="fixed">
			<parent link="${parent}"/>
			<child link="${name}_stand_link"/>
			<origin xyz="${xyz}" rpy="0 0 0" />
		</joint>

		<xacro:simple_box
			name = "${name}_stand_link"
			lwh  = "${stand_width} ${stand_width} ${height - chest_height}"
			xyz  = "0 0 ${(height - chest_height) / 2}"
			rpy  = "0 0 0"
			mass = "0.5"
			rviz_rgba = "0.5 0.5 0.5 1"
			material  = "Gazebo/Grey"
		/>

		<joint name="${name}_fixed_joint" type="fixed">
			<parent link="${parent}"/>
			<child link="${name}_link"/>
			<origin xyz="${xyz}" rpy="0 0 0" />
		</joint>

		<!-- Chest represented by a box -->

		<xacro:simple_box
			name = "${name}_link"
			lwh  = "${chest_length} ${chest_width} ${chest_height}"
			xyz  = "0 0 ${height - chest_height/2}"
			rpy  = "0 0 0"
			mass = "0.5"
			rviz_rgba = "1 0 0 1"
			material  = "Gazebo/Red"
			/>

		<joint name="${name}_top_frame_fixed" type="fixed">
			<parent link="${name}_link"/>
			<child link="${name}_top_frame"/>
			<origin xyz="0 0 ${height}" rpy="0 0 0" />
		</joint>

		<link name="${name}_top_frame">
            <inertial>
                <mass value="0.001" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001" />
            </inertial>
            <visual>
              <origin xyz="0 0 0" rpy="0 0 0" />
              <geometry>
                <box size="0.04 0.04 0.08" />
              </geometry>
              <material name="Red" />
            </visual>
            <collision>
              <origin xyz="0 0 0" rpy="0 0 0" />
              <geometry>
                <box size=".001 .001 .001" />
              </geometry>
            </collision>
        </link>

        <!-- IMU attached to the frame -->
        <joint name="${name}_imu_fixed" type="fixed">
            <parent link="${name}_top_frame"/>
            <child link="${name}_imu_link"/>
            <origin xyz="0.065 0.0 -0.12" rpy="0 0 -${M_PI/2}"/>
        </joint>
        <link name="${name}_imu_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.02 0.02"/>
                </geometry>
            </visual>
        </link>

	</xacro:macro>

</robot>
