<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       name="johnny_0" >

	<!-- The following included files set up definitions of parts of the robot body -->
	<include filename="$(find johnny_0_description)/urdf/common.xacro" />
	
	<!-- Description files -->
	<include filename="$(find johnny_0_description)/urdf/sensors/hokuyo_lx04_laser.urdf.xacro" />
	<include filename="$(find johnny_0_description)/urdf/base/base.urdf.xacro" />
	<include filename="$(find johnny_0_description)/urdf/wheel/wheel.urdf.xacro" />
	
	<!-- generic simulator_gazebo plugins for starting mechanism control, ros time, ros battery -->
	<include filename="$(find johnny_0_description)/gazebo/gazebo.urdf.xacro" />
	<!-- materials for visualization -->
	<include filename="$(find johnny_0_description)/urdf/materials.urdf.xacro" />	
	
	
	<!-- Now we can start using the macros included above to define the actual PR2 -->

	<!-- The first use of a macro.
       A macro like this will expand to a set of link and joint definitions, and to additional
       Gazebo-related extensions (sensor plugins, etc).  The macro takes an argument, name, 
       that equals "base", and uses it to generate names for its component links and joints 
       (e.g., base_link).  The included origin block is also an argument to the macro.  By convention, 
       the origin block defines where the component is w.r.t its parent (in this case the parent 
       is the world frame). For more, see http://www.ros.org/wiki/xacro -->
	   
	   
	<!-- Warning: eye-balled values for the laser position. -->
	<property name="base_laser_x" value="0.045" />
	<property name="base_laser_y" value="0.000" />
	<property name="base_laser_z" value="0.150" />
	<property name="base_laser_size_x" value="0.06" />
	<property name="base_laser_size_y" value="0.06" />
	<property name="base_laser_size_z" value="0.03" />
	<property name="base_laser_collision_offset_z" value="0.023" />

	<xacro:base name="base" />
	
	<xacro:wheel side="R" reflectSide="-1" face="B" reflectFace="-1" parent="base_link"/>

	<xacro:wheel side="R" reflectSide="-1" face="F" reflectFace="1" parent="base_link"/>
	
	<xacro:wheel side="L" reflectSide="1" face="B" reflectFace="-1" parent="base_link"/>
	
	<xacro:wheel side="L" reflectSide="1" face="F" reflectFace="1" parent="base_link"/>

	<!--xacro:bumblebee name="bumblebee" parent="head_head_link">
		<origin xyz="0.06 0 ${head_size_z/2 + bumblebee_size_z/2}" />
	</xacro:bumblebee-->



	
	
	
	
</robot>
