<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       name="johnny_0" >

	<!-- The following included files set up definitions of parts of the robot body -->
	<include filename="$(find irl_common_description)/urdf/common.xacro" />
	
	<!-- Description files -->
	<include filename="$(find irl_common_description)/urdf/jn0_torso/torso_box.urdf.xacro" />
	<include filename="$(find irl_common_description)/urdf/reddy_arm/arm.urdf.xacro" />
	<include filename="$(find irl_common_description)/urdf/jn0_head/head.urdf.xacro" />
	<include filename="$(find irl_common_description)/urdf/sensors/kinect.urdf.xacro" />
	
	<!-- generic simulator_gazebo plugins for starting mechanism control, ros time, ros battery -->
	<include filename="$(find jn0_description)/gazebo/gazebo.urdf.xacro" />
	<!-- materials for visualization -->
	<!-- FIXME  Materials from azimut -->
	<!--include filename="$(find jn0_description)/urdf/materials.urdf.xacro" /-->

	<!-- TODO screenshots in irl_common_description ? -->
	
	<!-- Base Azimut 3 + Laser -->
	<include filename="$(find az3_description)/robots/azimut_3.urdf.xacro" />

	<property name="torso_size_z" value="0.37921" />

	<xacro:jn0_torso_box
		name="torso"
		parent="base_link"
		xyz = "0 0 0.3089"
		stand_width  = "0.038"
		stand_height = "0.37038"
		chest_width  = "0.270"
		chest_length = "0.21583"
		chest_height = "${torso_size_z}"
		/>
	
	<xacro:reddy_arm side="R" reflect="-1" parent="torso_link"/>
	<xacro:reddy_arm side="L" reflect="1" parent="torso_link"/>
	
	<xacro:head name="head" parent="torso_link">
		<origin xyz="0.04 0 ${torso_size_z/2}" />
	</xacro:head>

	<xacro:kinect_static
		name="openni"
		parent="torso_link"
		xyz="0.17 0 ${torso_size_z/2}" rpy="0 0 0"
		angle="-0.35"
		/>
	
</robot>
